require "basics.launch"
require "basics.options"
require "basics.keymaps"
require "basics.autocmd"

spec "plugins.telescope"
spec "plugins.neogit"
spec "plugins.colorscheme"
spec "plugins.mason"
spec "plugins.lspconfig"
spec "plugins.nvimtree"
spec "plugins.devicons"
spec "plugins.autopair"
spec "plugins.none-ls"
spec "plugins.cmp"
spec "plugins.treesitter"
spec "plugins.schemastore"
spec "plugins.illuminate"
spec "plugins.noice"
spec "plugins.tabby"
spec "plugins.toggleterm"
spec "plugins.gitsigns"
spec "plugins.comment"
spec "plugins.lualine"
spec "plugins.breadcrumbs"
spec "plugins.navic"
spec "plugins.harpoon"
spec "plugins.neotest"


require "plugins.lazy"
