require "basics.launch"
require "basics.options"
require "basics.keymaps"
require "basics.autocmd"

spec "plugins.telescope"
spec "plugins.neogit"
spec "plugins.colorscheme"
spec "plugins.mason"
spec "plugins.lspconfig"
spec "plugins.nvimtree"
spec "plugins.devicons"
spec "plugins.autopair"
spec "plugins.none-ls"

require "plugins.lazy"
